### ISSUE TITLE
Bug tampilan ketika kode form langsung di-embed ke text area

### ISSUE THREAD

**Issue by nandasyo** [nadaft/Nadaft-KPR-Simulation#1]
Ada bug ketika form sudah terpasang di page

bug 1 : https://imgur.com/fat50U8

dan di halaman yang terpasang form terpasang 2x , dan muncul dibagian bawah header

bug 2 : https://imgur.com/bDyTPt3

bagaimana cara fix nya

**Comment by nandasyo** [comment]
Update Solusi :
Gunakan plugin "Advanced Custom Field" versi Pro
Kemudian buat Field Group pada Page yang ingin di embed Nadaft KPR Simulation
Step 1 : https://imgur.com/1dMAiAX
Step 2 : https://imgur.com/nXCR6xY

**Comment by nhnajibullah** [comment]
Terimakasih atas laporan dan solusinya

**Comment by gitfglllasd** [comment]
index.php line 21 ganti dengan :     include_once( plugin_dir_path( __FILE__ ) . 'views/form.php');

**Comment by nhnajibullah** [comment]
@gitfglllasd sudah release updatenya di [versi 1.1.3](https://github.com/nadaft/Nadaft-KPR-Simulation/releases/tag/1.1.3)
